import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Image from 'next/image'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <header className="flex flex-row justify-around bg-amber-500 text-sm text-neutral">
                    <div className="py-2 px-5">
                        <div className='flex gap-2'>
                            <div>
                                <svg xmlns="http://www.w3.org/2000/svg" className="icon icon-tabler icon-tabler-phone" width={20} height={20} viewBox="0 0 24 24" strokeWidth={1} stroke="currentColor" fill="none" strokeLinecap="round" strokeLinejoin="round">
                                    <path stroke="none" d="M0 0h24v24H0z" fill="none" />
                                    <path d="M5 4h4l2 5l-2.5 1.5a11 11 0 0 0 5 5l1.5 -2.5l5 2v4a2 2 0 0 1 -2 2a16 16 0 0 1 -15 -15a2 2 0 0 1 2 -2" />
                                </svg>
                            </div>
                            <div>
                                Kontak: 081234567890
                            </div>
                        </div>
                    </div>
                    <div className="py-2 px-5">
                        Cek Status Order
                    </div>
                </header>
                <nav className='flex flex-row px-8 py-2 gap-3 text-base text-neutral items-center shadow sticky'>
                    <div>
                        <Image src='/pukamiami.webp' width={120} height={0} alt='Pukamiami' />
                    </div>
                    <div className='rounded-lg hover:font-semibold hover:bg-zinc-100 cursor-pointer py-2 px-5'>
                        Kategori
                    </div>
                    <div className='relative w-9/12 min-w-[200px] ps-3'>
                        <div className="absolute grid w-5 h-5 place-items-center top-4 left-7 -translate-y-2/4">
                            <svg xmlns="http://www.w3.org/2000/svg" className="icon icon-tabler icon-tabler-search stroke-gray-400" width={22} height={22} viewBox="0 0 24 24" strokeWidth={2} stroke="currentColor" fill="none" strokeLinecap="round" strokeLinejoin="round">
                                <path stroke="none" d="M0 0h24v24H0z" fill="none" />
                                <path d="M10 10m-7 0a7 7 0 1 0 14 0a7 7 0 1 0 -14 0" />
                                <path d="M21 21l-6 -6" />
                            </svg>
                        </div>
                        <input type="text" className='border-neutral-400 border-opacity-60 border rounded-lg py-2 ps-12 pe-3 focus:border-amber-500 w-full appearance-none text-neutral leading-tight focus:outline-none focus:shadow-outline' placeholder='Cari di Pukamiami' />
                    </div>
                    <div className='ms-auto flex gap-2 rounded-lg hover:bg-zinc-100 cursor-pointer p-3'>
                        <svg xmlns="http://www.w3.org/2000/svg" className="icon icon-tabler icon-tabler-user stroke-neutral-600" width={24} height={24} viewBox="0 0 24 24" strokeWidth={2} stroke="currentColor" fill="none" strokeLinecap="round" strokeLinejoin="round">
                            <path stroke="none" d="M0 0h24v24H0z" fill="none" />
                            <path d="M8 7a4 4 0 1 0 8 0a4 4 0 0 0 -8 0" />
                            <path d="M6 21v-2a4 4 0 0 1 4 -4h4a4 4 0 0 1 4 4v2" />
                        </svg>
                        Afandi Aziz
                    </div>
                </nav>
                {children}
            </body>
        </html>
    )
}
